### PR TITLE
🐛 FIX: Use separate notToThrow method to fix default regex

### PR DESCRIPTION
**Pull request by michaelborn**
Resolves TESTBOX-357.

### CODE REVIEW

**Comment by michaelborn** [comment]
Happy to refactor if necessary. I chose to implement a separate `notToThrow()` assertion, because (I thought) it's the cleanest way to maintain a different default regex for each behavior.

**Comment by lmajano** [comment]
Could you add a test for it please?

**Comment by michaelborn** [comment]
See new test, Luis. I confirmed this test fails on the `development` branch, and passes on my branch.

https://github.com/Ortus-Solutions/TestBox/pull/142/files#diff-715d8417d7c5421fab5727f691e8675ba8b78dda50714d6bdcb0ffda939a990bR385-R392

**Comment by lmajano** [comment]
The failure is a cfformat issue.  Weird!!

**Pull request merged**
