### PR TITLE
Fix path bugs and syntaxhighlighter issue

### PR DESCRIPTION
**Pull request by iurquiza**

### CODE REVIEW

**Comment by timbeadle** [comment]
We pull latest Testbox to run our test suite, and this seems to have broken our test running.

We get the exception: "Coverage option [pathToCapture] does not point to a real and absolute directory path."

May have to pin to 2.8.0 instead of using latest, but just wanted to let you know.

**Comment by timbeadle** [comment]
@lmajano We're not using the code coverage functionality, no. Just running MXUnit-style unit tests with Testbox. I'd have to chat with our Ops team to find out how the test runner is invoked.

**Comment by lmajano** [comment]
Ok, if you can let me know, then I can try to reproduce this.

**Comment by iurquiza** [comment]
@timbeadle can you please also let me know what operating system you are running it on?

**Comment by timbeadle** [comment]
@lmajano OK, it looks like our CI server just makes a cURL request to the CF server to get the junit-format test results.

@iurquiza It's Centos 7.

**Comment by bdw429s** [comment]
@timbeadle Can yo please include the detail of that error as it should include the actual path in question so we can debug?  Also, please provide your `runner.cfm`.

here is the error getting thrown and the check that precedes it:
```
if( !directoryExists( opts.pathToCapture ) ) {
	throw( message='Coverage option [pathToCapture] does not point to a real and absolute directory path.', detail=opts.pathToCapture );
}
```

**Comment by timbeadle** [comment]
@bdw429s here's the exception detail.

[testbox-exception.txt](https://github.com/Ortus-Solutions/TestBox/files/3033079/testbox-exception.txt)

**Comment by timbeadle** [comment]
The "runner".cfm (actually index.cfm in our codebase) is this:
```
<cfscript>
param name='url.reporter' default='Junit';

if (url.keyExists('directory')) {
	testbox = new testbox.system.TestBox();
	testbox.addDirectories(url.directory);
	results = testbox.run(reporter=url.reporter);
	content reset=true;
	WriteOutput(results);
} else {
	WriteOutput('The url parameter "directory" is required.');
}

</cfscript>
```

**Comment by bdw429s** [comment]
Thanks @timbeadle If you look closely at that error you'll see that the error is about the path to capture, but the path being used is your coverage report path!  This is a bug in TestBox that was introduced in one of the recent pushes.  I actually noticed it last night while looking at the code and pushed a fix yesterday.  Please pull the latest bleeding edge and see if it is resolved.

**Comment by timbeadle** [comment]
Thanks @bdw429s. As I mentioned, we've pinned to 2.8.0 now, as we don't really want to pull from latest git just in case. Perhaps we'll try a future tagged release.

**Comment by bdw429s** [comment]
@timbeadle I would like it if you could test though.  We don't really have anyone on Linux to test and there are specifics in the file system of Linux that hit code I can't test on WIndows (such as paths named `/root` in the actual file system.  With the magic of package managers, it's not hard to quickly pull down a version and test.

```
install testbox@be --force
... do some testing...
install testbox@2.8.0 --force
```

Otherwise, we'll not really know if we fixed your issue or not and we're on the precipice of releasing TestBox 3.0 at this point. so we want to make sure everything is kosher.

**Comment by timbeadle** [comment]
@bdw429s OK, I'll chat with ops and see if we can do that. Thanks again.

**Comment by timbeadle** [comment]
@bdw429s Your fix has been verified as working on Linux 👍

**Comment by bdw429s** [comment]
@timbeadle Great, thanks!

**Pull request merged**
