### PR TITLE
switch pass/failed/error colors,

### PR DESCRIPTION
**Pull request by iwburns**
these colors are a bit more
color-blind-friendly

### CODE REVIEW

**Comment by iwburns** [comment]
Hello, I have red-green colorblindness and was having a bit of trouble telling the difference between the pass/fail colors in my test results.

I totally understand if you don't want to change these colors, but I thought I'd come up with some colors that have a bit more contrast and suggest them in case you're open to changing this.

**Comment by iwburns** [comment]
Here are some before and after images to make this easier to compare:
before:
before
after:
after

**Comment by elpete** [comment]
I think this is awesome!  Thank you!

**Comment by iwburns** [comment]
No problem!  All I did was use a color wheel to select a red/green/orange combo that was more distinct to my own eye.

Since colorblindness varies from person to person (and because there is more than one type of colorblindness) there may be a red/green/orange color combination out there that will work even better for more colorblind people, but at the very least these are in the right ball-park I think.

**Pull request merged**
