### PR TITLE
TESTBOX-333: CONTRIBUTING.md section headings and explanation of what the sections ought to contain (NOT TO BE MERGED!)

### PR DESCRIPTION
**Pull request by adamcameron**
As requested in TESTBOX-333 by @lmajano. Here's an explanatory skeleton of what one might expect to have in a CONTRIBUTING.md. Most of the content needs to come from your team though, I think.

We can discuss the content here, and I'm happy to keep working on the doc until it's suitable for inclusion in the project.

### CODE REVIEW

**Comment by zspitzer** [comment]
Code should follow the ortus style guide?

**Comment by lmajano** [comment]
Thanks so much @adamcameron I will work on it using this blueprint.  Looks great

**Comment by lmajano** [comment]
First try added to repo, please revise and suggest @adamcameron . Thanks for the inspiration

**Comment by adamcameron** [comment]
Nice work mate. Cheers.

**Pull request closed without merging**
