### PR TITLE
#12 RemoteFacade MXUnit compatiblity

### PR DESCRIPTION
**Pull request by denuno**
This fleshes out MXUnit compatibility, which allows folks to use the MXUnit Eclipse plugin.  Besides adding the stuff needed for RemoteFacade, it also tweaks BaseRunner-- MXUnit doesn't require tests to have "test" in their function names, so this tweak runs those tests while in mxunit compatibility mode instead of silently skipping them.

### CODE REVIEW

**Comment by lmajano** [comment]
Thanks @denuno , build is failing though?

**Comment by bdw429s** [comment]
@lmajano The build looks like it was an unrelated failure.  I'd restart the build but I don't have permissions.  Can you give me permissions to this project?

**Comment by lmajano** [comment]
Build restarted and you have permissions now.

**Comment by lmajano** [comment]
I am not sure if this is relevant anymore. Thoughts

**Comment by bdw429s** [comment]
Closing since the trail seems to have gone cold here.  If this is still something we need to add, then please open a new pull that's up to date and we'll try to get it straightened out.

**Pull request closed without merging**
