### PR TITLE
URL convention inside a CFC? Is this necessary anymore?

### PR DESCRIPTION
**Pull request by goochjj**

### CODE REVIEW

**Comment by lmajano** [comment]
It is, due to been able to execute TestBox direclty via http/s

**Comment by bdw429s** [comment]
@lmajano Can you give an example of what you're talking about as I don't think that's actually the case.  One can (and should) pass in parameters to a remote method that are actually handled as arguments to the remote method.  ColdFusion automatically passes URL parameters into the remote method as the arguments scope.    Furthermore, Joe's pull actually fixes a _bug_ in TestBox.  Consider the following URL:
```
http://localhost/tests/specs/unit/myServiceTest.cfc?method=runRemote&testSuites=foo
```
TestBox actually incorrectly adds the `foo` test suite twice to the internal array! This is because the param comes in through the `runRemote()` call and then is added a second time by the extraneous code that he removed in this pull.

If anything, we just need to add arguments for `testMethod` to the `BaseSpec.runRemote()` so we can pass them along like the others.

**Comment by bdw429s** [comment]
@lmajano ? It would be nice to get this added in prior to the pending TestBox release.

**Comment by lmajano** [comment]
The truth is that I have to recall all of this. But there was a reason to do it. It was not by accident.

**Comment by bdw429s** [comment]
@lmajano I've racked my brains and I can't think of why we'd need it.  In addition to being a really bad break of encapsulation it's literally causing bugs in TestBox where URL params are being added twice.  If we can't think of the use, maybe it's time to get rid of it?  I'm guessing it was a convenient "hack" back in the day for runners that didn't properly pass URL variables through.

**Pull request closed without merging**
