### PR TITLE
Fix compatibility for ACF 10 by removing member functions

### PR DESCRIPTION
**Pull request by elpete**

### CODE REVIEW

**Comment by lmajano** [comment]
Can you remind me why we need `cf10` support?

**Comment by elpete** [comment]
Because this is a minor release.  You can't break compatibility on a minor release.  I have dozens of repos failing their tests now because of this.  Failing there tests _with no changes to their own code_.

**Comment by elpete** [comment]
If you want to drop ACF 10, that's fine, but it should be TestBox 3.0.0

**Comment by elpete** [comment]
In the meantime, I think we owe it to the community to release a patch to fix this.

**Comment by lmajano** [comment]
Thanks, will revise. I actually thought cf10 supported `each`

**Pull request merged**
