### PR TITLE
Update Expectation.cfc to make toMatchWithCase consistent.

### PR DESCRIPTION
**Pull request by gpickin**
Not sure if we want to do something with backwards compat. 
But I think this API isn't well known or used, or someone would have complained.

Thoughts?

### CODE REVIEW

**Comment by lmajano** [comment]
Travis is failing @gpickin

**Comment by gpickin** [comment]
It only failed on 2016. Any ideas why? How do I debug this?

**Comment by bdw429s** [comment]
@gpickin Click on the "details" link above to go to travis and click on the 2016 build and scroll through the logs.  The error is here:
https://travis-ci.org/Ortus-Solutions/TestBox/jobs/365359238#L597

> Invalid construct: Either argument or name is missing.
 
Secure profile is on by default, or at least robust errors are off by default so you'd need to change the build itself to set some settings via CFConfig otherwise to see the location of the error.

**Comment by lmajano** [comment]
merged manully.,

**Pull request closed without merging**
