### PR TITLE
Recursive around each middleware

### PR DESCRIPTION
**Pull request by elpete**
# Change Summary

Add the ability to run aroundEach blocks recursively in a
middleware-like fashion from the oldest parent down to the current spec.

### CODE REVIEW

**Comment by elpete** [comment]
I added one new feature: an `aroundEvery` lifecycle method.

It's an optional lifecycle method that would be the first `aroundEach` middleware called, if defined.

The main use case here is for database transaction rollbacks after every test.

If accepted, I plan to make a pull request against ColdBox to add a simple DatabaseTest component that implements the transaction rollbacks automatically.  (And possibly even a CommandBox scaffolding pull request. 😊)  

Thanks!

**Comment by elpete** [comment]
Also, new tests are `AroundEveryTest` and `NestedAroundEachTest`.

**Comment by lmajano** [comment]
@elpete I am confused on the purpose of `aroundEvery`? can you explain

**Comment by elpete** [comment]
We've been doing some database testing and I want to rollback a transaction after every test.  With recursive `aroundEach`, I could put it in the highest `describe` block, but `aroundEvery` was my attempt to do that in (what I thought) was a more readable way.

The `aroundEvery` way:

```js
component extends="coldbox.system.testing.BaseTestCase" appMapping="/" {

  function aroundEvery(spec) {
    transaction action="begin" {
      try {
        arguments.spec.body();
      }
      catch (any e) {
        rethrow;
      }
      finally {
        transaction action="rollback";
      }
    }
  }

  function run() {
    describe("an actual suite (not just a wrapper suite for an `aroundEach`", function() {
      // tests as normal
    });
  }

}
```

is functionally equivalent to

```js
component extends="coldbox.system.testing.BaseTestCase" appMapping="/" {

  function run() {
    describe("wrapper so I can use a global `aroundEach`", function() {
      function aroundEach(spec) {
        transaction action="begin" {
          try {
            arguments.spec.body();
          }
          catch (any e) {
            rethrow;
          }
          finally {
            transaction action="rollback";
          }
        }
      }

      describe("an actual suite, not just a wrapper", function() {
        // tests as normal
      });

    });
  }

}
```

To restate one more way, `aroundEvery` is for when you want to execute an `aroundEach` for every single test in your `run()` method, no matter which suite it is in.

But really, it's a little bit of syntactical sugar, as my example hopefully shows.

**Comment by elpete** [comment]
If wanted, I can separate these pull requests.  I realize that one was a planned feature and one was my own invention. 😄

**Comment by lmajano** [comment]
Sorry @elpete but I don't get the difference between them. They are both providing the same thing in my opinion.

**Comment by elpete** [comment]
That's fine.  How do you feel about the recursive `aroundEach` part?  I can close this and commit that as a separate pull request.

**Comment by lmajano** [comment]
Sorry @elpete been a little swamped. I think the problem with `aroundEvery` is that it does not follow the `each` precedence of `before and after`.  Therefore, I would prefer to stick to the precedence of `each`.  Therefore can you close and just re-submitt using the recursive `aroundEach()` approach

**Pull request closed without merging**
